# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspeech.proto\x12\x06speech\"8\n\rStreamRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61udio_chunk\x18\x02 \x01(\x0c\"\xa5\x01\n\x0eStreamResponse\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .speech.StreamResponse.EventType\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nsilence_ms\x18\x03 \x01(\x05\"A\n\tEventType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07PARTIAL\x10\x01\x12\t\n\x05\x46INAL\x10\x02\x12\x0b\n\x07SILENCE\x10\x03\x32H\n\x06Speech\x12>\n\tRecognize\x12\x15.speech.StreamRequest\x1a\x16.speech.StreamResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STREAMREQUEST']._serialized_start=24
  _globals['_STREAMREQUEST']._serialized_end=80
  _globals['_STREAMRESPONSE']._serialized_start=83
  _globals['_STREAMRESPONSE']._serialized_end=248
  _globals['_STREAMRESPONSE_EVENTTYPE']._serialized_start=183
  _globals['_STREAMRESPONSE_EVENTTYPE']._serialized_end=248
  _globals['_SPEECH']._serialized_start=250
  _globals['_SPEECH']._serialized_end=322
# @@protoc_insertion_point(module_scope)
